// Types for API responses (kept for compatibility)
export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export interface ChatResponse {
  content: string;
}

export interface RevisionResponse {
  revised: string;
  original: string;
}

export interface Suggestion {
  id: string;
  rule: string;
  description: string;
  confidence: number;
  status: 'missing' | 'partial' | 'met';
  evidence: string | null;
}

export interface AnalysisResponse {
  suggestions: Suggestion[];
  clinical_note: string;
}

export interface OllamaError {
  error: string;
}

// Hardcoded responses for demo version
const DEMO_CHAT_RESPONSE = {
  content: 'This is a hardcoded response for the demo version. In the full version, this would be generated by an AI model.'
};

const DEMO_REVISION_RESPONSE = {
  revised: `Dear Insurance Provider,

I am writing to request prior authorization for MRI of the lower extremity (CPT: 73721) for my patient, John Smith.

Clinical Summary:
The patient presents with chronic lower back pain that has persisted for over 6 months. The pain is described as dull and aching, rated 7/10 on the pain scale. The pain radiates down the left leg, consistent with radiculopathy.

Treatment History:
The patient has tried conservative management including:
- Over-the-counter NSAIDs with minimal relief
- Physical therapy for 4 weeks with no significant improvement
- Home exercise program with no relief
- Activity modification with limited improvement

Functional Limitations:
The patient reports difficulty with walking more than 15 minutes, sitting for extended periods, and climbing stairs. These limitations significantly impact daily activities and work performance.

Clinical Findings:
Physical examination reveals positive straight leg raise test on the left side, decreased sensation in the L5 dermatome, and reduced strength (4/5) in the left foot dorsiflexion.

Imaging:
Previous X-rays show degenerative changes at L4-L5 level. An MRI is medically necessary to evaluate for suspected disc herniation and nerve root compression.

Thank you for your consideration of this request. Please feel free to contact our office if you require any additional information.

Sincerely,
Dr. Smith`,
  original: `Dear Insurance Provider,

I am writing to request prior authorization for MRI of the lower extremity (CPT: 73721) for my patient, John Smith.

Clinical Summary:
The patient presents with chronic lower back pain that has persisted for over 6 months. The pain is described as dull and aching, rated 7/10 on the pain scale. The pain radiates down the left leg, consistent with radiculopathy.

Treatment History:
The patient has tried conservative management including:
- Over-the-counter NSAIDs with minimal relief
- Physical therapy for 4 weeks with no significant improvement

Thank you for your consideration of this request. Please feel free to contact our office if you require any additional information.

Sincerely,
Dr. Smith`
};

const DEMO_ANALYSIS_RESPONSE = {
  suggestions: [
    {
      id: 's1',
      rule: 'Document failed conservative treatment',
      description: 'Need to document at least 6 weeks of conservative treatment',
      confidence: 85,
      status: 'partial' as 'partial',
      evidence: 'Patient has tried over-the-counter NSAIDs with minimal relief. Physical therapy was attempted for 4 weeks with no significant improvement.'
    },
    {
      id: 's2',
      rule: 'Specify functional limitations',
      description: 'Document how pain affects activities of daily living',
      confidence: 90,
      status: 'missing' as 'missing',
      evidence: null
    },
    {
      id: 's3',
      rule: 'Include physical exam findings',
      description: 'Document relevant physical examination findings',
      confidence: 75,
      status: 'missing' as 'missing',
      evidence: null
    },
    {
      id: 's4',
      rule: 'Missing documentation of symptom duration',
      description: 'Need to clearly specify how long symptoms have been present',
      confidence: 95,
      status: 'met' as 'met',
      evidence: 'Patient presents with chronic lower back pain that has persisted for over 6 months.'
    }
  ],
  clinical_note: `Patient presents with chronic lower back pain that has persisted for over 6 months. Pain is described as dull and aching, rated 7/10 on the pain scale. Pain radiates down the left leg. Patient has tried over-the-counter NSAIDs with minimal relief. Physical therapy was attempted for 4 weeks with no significant improvement. MRI shows L4-L5 disc herniation with nerve root compression. Patient is requesting referral to pain management specialist for epidural steroid injections.`
};

/**
 * Send a chat message (hardcoded for demo)
 */
export async function sendChatMessage(
  messages: ChatMessage[],
  model: string = 'llama3.2'
): Promise<ChatResponse> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1000));
  return DEMO_CHAT_RESPONSE;
}

/**
 * Revise a draft (hardcoded for demo)
 */
export async function reviseDraft(
  draft: string,
  instructions: string = 'Check and revise this draft for clarity, coherence, and correctness.',
  model: string = 'llama3.2'
): Promise<RevisionResponse> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  return {
    ...DEMO_REVISION_RESPONSE,
    original: draft // Use the actual draft as the original
  };
}

/**
 * Analyze a clinical note (hardcoded for demo)
 */
export async function analyzeClinicalNote(
  clinicalNote: string,
  model: string = 'llama3.2'
): Promise<AnalysisResponse> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  return {
    ...DEMO_ANALYSIS_RESPONSE,
    clinical_note: clinicalNote // Use the actual clinical note
  };
}

/**
 * Get available models (hardcoded for demo)
 */
export async function getAvailableModels(): Promise<string[]> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1000));
  return ['llama3.2', 'llama4.0'];
}

/**
 * Check if the API is available (always returns true for demo)
 */
export async function checkApiHealth(): Promise<boolean> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return true;
}
